![imagen](./img/ejercicios.png)

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [3]:
import numpy as np
np. __version__

'2.2.4'

## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [4]:
my_array = np.array([0,1,2,3,4,5,6,7,8,9])
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Ejercicio 3
Crea un array 3x3, que sea todo a True

In [9]:
np.full((3, 3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Ejercicio 4
Extrae todos los impares de `my_array`

In [13]:
print(my_array[1::2]) 


[1 3 5 7 9]


## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [15]:
my_array[1::2] = -1
my_array

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

In [20]:
np.where(my_array %2 ==1, -1, my_array)


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [26]:
np.reshape(my_array, (2, 5))

array([[ 0, -1,  2, -1,  4],
       [-1,  6, -1,  8, -1]])

## Ejercicio 8
Concatena los siguientes arrays verticalmente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [45]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.vstack([a, b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Ejercicio 9
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [47]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.hstack([a, b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa la función `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [52]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a, b)

array([2, 4])

## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

In [54]:
help(np.concatenate)

Help on _ArrayFunctionDispatcher in module numpy:

concatenate(...)
    concatenate(
        (a1, a2, ...),
        axis=0,
        out=None,
        dtype=None,
        casting="same_kind"
    )
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
        provided together with `out`.
    
        .. versionadded:: 1

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento de `my_array`
3. Accede al último elemento de `my_array`
4. Imprime por pantalla los numeros del 1 al 7 de `my_array`

In [58]:
my_array = np.array([0,1,2,3,4,5,6,7,8,9])
print(my_array[0])
print(my_array[-1])
print(my_array[1:8])

0
9
[1 2 3 4 5 6 7]


## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

In [61]:
my_matrix= np.random.randint(0, 10, (3, 3))
print(my_matrix)

[[8 1 2]
 [7 9 4]
 [1 4 8]]


## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

In [69]:
secuencia = np.arange(1,50,3)
print(" La secuencia va de 3 en 3: ", secuencia)

 La secuencia va de 3 en 3:  [ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]


## Ejercicio 15
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

In [80]:
secuenta_matric= np.random.randint(0,60, size=(4,5,3))
print(secuenta_matric)

[[[14 53 51]
  [29 30 47]
  [23 57  2]
  [13  3 31]
  [51 35 16]]

 [[11 49  9]
  [10  9 29]
  [20 31 56]
  [12 55 58]
  [31  0 34]]

 [[55 51 14]
  [12 16 49]
  [56 40 20]
  [24 11 51]
  [52 59 13]]

 [[18 49 29]
  [45 46 12]
  [33 32 34]
  [13 14 21]
  [ 9  4 59]]]


## Ejercicio 16
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

In [85]:
matrizfalsa= np.full((10,1), False)
np.reshape(matrizfalsa, (2,5))

array([[False, False, False, False, False],
       [False, False, False, False, False]])

## Ejercicio 17
Dado el siguiente array

```Python
x = np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuánta es la longitud cada dimensión?

In [99]:
x = np.random.randint(10, 20, size = (5,2,6))
print(x)
print("Tiene", x.size, "elementos")
print("Tiene", x.ndim, "dimensiones")
print("Cada dimension tiene", x.shape, "longitud")

[[[18 10 19 18 17 16]
  [12 14 17 13 18 15]]

 [[10 16 15 18 13 17]
  [15 11 11 10 13 17]]

 [[18 19 18 16 18 15]
  [11 19 19 10 13 12]]

 [[15 12 16 17 10 18]
  [16 10 10 17 16 12]]

 [[16 10 15 18 17 12]
  [11 17 10 13 15 16]]]
Tiene 60 elementos
Tiene 3 dimensiones
Cada dimension tiene (5, 2, 6) longitud
