![imagen](./img/ejercicios.png)

In [261]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [262]:
my_array = np.arange(10)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [263]:
print(my_array[::-2])

[9 7 5 3 1]


In [264]:
print(my_array[my_array % 2 == 1][::-1])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [265]:
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [266]:
print(my_array[-2:-4:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [267]:
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [268]:
print(my_array[2::-1])

[2 1 0]


In [269]:
print(sorted(my_array[:3],reverse=True))

[np.int64(2), np.int64(1), np.int64(0)]


In [270]:
np.take(my_array, [2,1,0])

array([2, 1, 0])

## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [271]:
my_matrix = np.arange(1,21).reshape(4,5)
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [272]:
my_matrix.T

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

In [273]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [274]:
print(my_matrix[::-1,::-1])

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [275]:
print(np.flip(my_matrix))

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [276]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [277]:
print(my_matrix[:2,:2])

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [278]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [279]:
print(my_matrix[::2,::2])

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [280]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [281]:
print(my_matrix[:3,::-1])

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [282]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

In [283]:
x == "Loro"

array([ True, False, False,  True, False])

In [284]:
x[x == "Loro"]

array(['Loro', 'Loro'], dtype='<U5')

In [285]:
print(np.where(x== "Loro")[0])

[0 3]


In [286]:
print(np.where(x == "Loro")[0])

[0 3]


In [287]:
x[np.where(x == "Loro")]

array(['Loro', 'Loro'], dtype='<U5')

In [288]:
# np.where(x == "Loro", x, np.nan)

## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [289]:
x = np.arange(20).reshape(2,5,2)
print(x)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


In [290]:
print(x.ndim)
print(x.shape)
print(x.size)

3
(2, 5, 2)
20


In [291]:
x = np.arange(20).reshape(10,2)
print(x)
m1,m2 = np.vsplit(x,[5])
print()
print(m1)
print()
print(m2)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [292]:
array10_0s= np.zeros(10)
print(array10_0s)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [293]:
array10_0s[3] = 1
print(array10_0s)

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [294]:
vde10a29 = np.arange(10,50)
print(vde10a29)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [295]:
print(vde10a29[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [1, 2 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [296]:
envector= np.array([1,2,0,0,4,0])
print(envector)
print()

def encuentra_no_cero(vector):
    return np.where(vector != 0)

print(encuentra_no_cero(envector))

[1 2 0 0 4 0]

(array([0, 1, 4]),)


## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [297]:
mat10x10= np.random.randint(0,100,100)
mat10x10= mat10x10.reshape(10,10)
print(mat10x10)

[[38 83 79 10 40 55 24 20 97 20]
 [50 86 99 59 59 25 23 69 75 98]
 [70 68 30 93 57 85 27 70 65 76]
 [87 22  5 94 14  3 32 62 79 64]
 [71 41  4 73 26 17 42 17 88 94]
 [47 44 95 69  9 46 49 91 86 78]
 [87 44 98 24 60 46 95 51 48 45]
 [66  4  6 36 72 27  9 60 24 77]
 [71 66 57 19 77 38 68 82 54 49]
 [50 92  3 17 19 46 60 56 63 98]]


In [309]:
print(np.min(mat10x10))
print(np.max(mat10x10))

3
99


## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [299]:
vecmedia= np.random.randint(0,11111,30)
print(vecmedia)
print()

print(round(np.mean(vecmedia),2))

[3233 2860 4389 2527 6625 2380 5700 1502 9084 6788 8686 5877 5138 5207
 8175  363 2858 3677 4398 4950 8954 5631 2689 7213 7957 6203 2850 9916
 7906 2663]

5213.3


## Ejercicio 15
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [300]:
meanstd= np.random.randint(323,500,25)
meanstd= meanstd.reshape(5,5)
print(meanstd)

[[431 362 340 434 410]
 [358 341 361 436 441]
 [331 437 361 468 343]
 [350 411 411 471 427]
 [474 455 330 440 471]]


In [301]:
mean_de_meanstd=np.mean(meanstd)
print(mean_de_meanstd)

403.76


In [302]:
standard=np.std(meanstd)
print(standard)

49.28633076219003


In [303]:
meanstd= (meanstd-mean_de_meanstd)/standard

In [304]:
print(np.round(meanstd, decimals=3))

[[ 0.553 -0.847 -1.294  0.614  0.127]
 [-0.928 -1.273 -0.868  0.654  0.756]
 [-1.476  0.674 -0.868  1.303 -1.233]
 [-1.091  0.147  0.147  1.364  0.472]
 [ 1.425  1.04  -1.497  0.735  1.364]]


## Ejercicio 16
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [305]:
secunum= np.arange(0,11)
print(secunum)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [306]:
secunum[3:9]

array([3, 4, 5, 6, 7, 8])

In [307]:
secunum[3:9]= -1
print(secunum)

[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]


In [308]:
nuevosecunum= secunum
print(nuevosecunum)   

[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]
